# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.0
    # Use build with args to set proper permissions
    build:
      context: .
      args:
        GROUPID: 20  # Replace with output of 'id -g'
        GROUPNAME: staff  # Replace with output of 'id -gn' 
        USERID: 501  # Replace with output of 'id -u'
        USERNAME: ceciliacallejas  # Replace with output of 'echo $USER'
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll:Z
      # Add a named volume for the cache directory
      - jekyll_cache:/srv/jekyll/.jekyll-cache
    environment:
      - JEKYLL_ENV=development

# Define the named volume
volumes:
  jekyll_cache: